runtime: python39
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  DB_NAME: 'scorecard'
  INSTANCE_CONNECTION_NAME: 'automationwbrise:us-east5:scorecard'
  DB_USER: 'awfasano'
  DB_PASSWORD:
  DB_PASS: 
  DB_HOST: '34.162.122.101'
  DB_PORT: '5432'
  DATABASE_URL: 

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto
